service:
  name: api
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x

functions:
  createCheckoutSession:
    handler: createCheckoutSession.handle
    events:
      - http:
          method: post
          path: checkoutsession
          cors: true
